name: Build and push docker image on push or PR to main branch to docker hub

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
    types:
      - 'closed'

jobs:
  check-install-packages:
    name: Validate package installation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch at $GITHUB_WORKSPACE
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
  docker:
    name: Build and push to docker hub
    needs: check-install-packages
    runs-on: ubuntu-latest
    environment: 'test'
    steps:
      - name: Checkout branch at $GITHUB_WORKSPACE
        uses: actions/checkout@v4

      - name: Create firebase credential file
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: firebase.keys.json
          json: ${{ secrets.FIREBASE_KEY_JSON }}
          dir: ./src/common/configs

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE_TAG }}
